### ISSUE TITLE
Menambahkan Beberapa Informasi Komunitas Atau Organisasi

### ISSUE THREAD

**Issue by r17x** [kpmks/kumpulan-komunitas-makassar#1]
Menambahkan Beberapa Informasi Komunitas Atau Organisasi yang berada di kota makassar dan sekitarnya.

untuk memudahkan kolaborasi bersama atau kegiatan - kegiatan seputar IT/Development Di kota makassar

regards, ri7nz

**Comment by arhen** [comment]
d close yah. udah dlm progress,
